@startmindmap

+ Cruelty Free Investments
++ Promotions
+++ Surveys to connect with people
+++ Visual graphics
+++ Infographics
+++ Jain Media
++++ Script required to tell the story
-- Investment Journey
--- Impact of Investments
---- Lifestyle factors
---- Data (numbers)
----- Silk industry (textile ?)
--- What and How are Cruelty Free Investments
---- What assets once can invest in?
----- Mutual funds are not green
----- Equity
--- Challenges in implemention
---- Difficulty in equity investments
----- Market fear
----- Lack of knowledge
----- Lack of time
---- Portfolio management : Goal achievement
----- Balanced portfolio needs debt options
----- Lack of options other than stocks
@endmindmap